source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ScrollViewRefresh' do

    pod 'AFNetworking', '~> 3.2.0'
    pod 'YYModel'
    pod 'MJRefresh', '~> 3.1.15'
    pod 'YYModel'
    pod 'SDWebImage'

end
